name: Trigger auto deployment for my-nest-project

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/my-nest-project-AutoDeployTrigger-87d9fd33-4e85-444f-aed6-55dd3729c0ed.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MYNESTPROJECT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYNESTPROJECT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYNESTPROJECT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: nestreg.azurecr.io
          registryUsername: ${{ secrets.MYNESTPROJECT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYNESTPROJECT_REGISTRY_PASSWORD }}
          containerAppName: my-nest-project
          resourceGroup: my-nest-project
          imageToBuild: nestreg.azurecr.io/my-nest-project:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


